---
- name: Clone VM and rename
  hosts: localhost
  vars_files:
    - ~/articles/proxmox # Reference the encrypted vault file directly

  tasks:
    - name: Clone VM
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"        # Replace with your Proxmox server IP
        api_user: "{{ api_user }}"   # Variables are now accessible directly
        api_password: "{{ api_password }}"   # from the vaul
        node: "pensask"                      # Replace with the specific node name in Proxmox
        vmid: 107                             # ID of the VM to clone
        clone: NewClone                        # Name for the cloned VM
        name: NewVM 
        pool: CyberSecurity                  # Name of the pool to place the VM in
        full: true                           # Set to true for a full clone
      delegate_to: localhost
